## 2026-09-22 numpy 학습

In [2]:
# import 관련 명령은 notebook의 처음 cell에서 한번 실행하는 것을 권장
import numpy as np

In [3]:
a = np.array([[1,2,3],[4,5,6]], dtype=np.float32)
b = [[1,2,3], [4,5,6]]
print(a, b)
print(type(a), type(b))

[[1. 2. 3.]
 [4. 5. 6.]] [[1, 2, 3], [4, 5, 6]]
<class 'numpy.ndarray'> <class 'list'>


In [5]:
print(np.shape(a))

(2, 3)


In [6]:
b=[[1,2], [3,4,5]]
print(len(b), len(b[0]), len(b[1]))

2 2 3


## numpy의 ndarray 타입은 하위 차원의 크기는 동일해야함. 예를 들면, (2,3)인 경우 모든 행의 크기는 3이어야 함 
## 다차원 list인 경우에는 각 차원의 크기가 동일할 필요는 없다.

In [7]:
print(a.ndim, a.shape, a.dtype)
print(dir(a))

2 (2, 3) float32
['T', '__abs__', '__add__', '__and__', '__array__', '__array_finalize__', '__array_function__', '__array_interface__', '__array_namespace__', '__array_priority__', '__array_struct__', '__array_ufunc__', '__array_wrap__', '__bool__', '__buffer__', '__class__', '__class_getitem__', '__complex__', '__contains__', '__copy__', '__deepcopy__', '__delattr__', '__delitem__', '__dir__', '__divmod__', '__dlpack__', '__dlpack_device__', '__doc__', '__eq__', '__float__', '__floordiv__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__iand__', '__ifloordiv__', '__ilshift__', '__imatmul__', '__imod__', '__imul__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__ior__', '__ipow__', '__irshift__', '__isub__', '__iter__', '__itruediv__', '__ixor__', '__le__', '__len__', '__lshift__', '__lt__', '__matmul__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__ra

### numpy의 배열 생성 (ones, zeros) : ones, 모든 원소가 1임, zeros, 모든 원소가 0임


In [8]:
a = np.ones((2,3), np.float32)
b = np.ones(10, np.uint8)
print(a, b)

[[1. 1. 1.]
 [1. 1. 1.]] [1 1 1 1 1 1 1 1 1 1]


In [10]:
print(a.shape, b.shape)

(2, 3) (10,)


In [11]:
b = b.reshape((10,1)) # vector (10,) -> matrix (10, 1) 로 변환
print(a.shape, b.shape)

(2, 3) (10, 1)


In [12]:
c = np.zeros((1,2,3), np.float32)
print(c.shape, c)

(1, 2, 3) [[[0. 0. 0.]
  [0. 0. 0.]]]


In [13]:
a_shape = a.shape
d = np.zeros(a_shape, a.dtype)
print(a.shape, d.shape, a.dtype, d.dtype)

(2, 3) (2, 3) float32 float32


In [14]:
e = np.zeros_like(a)
print(e.shape, e.dtype)

(2, 3) float32


In [15]:
# arange, range(start, end, increment)
print(np.array(list(range(2,5)), dtype=np.float32))

[2. 3. 4.]


In [16]:
f = np.arange(2, 5, dtype=np.float32)
print(f)

[2. 3. 4.]


In [17]:
# arange from 1 to 3*3*4, reshape, (3,3,4) 배열을 생성
g = np.arange(1, 3*3*4+1, dtype=np.float32).reshape(3,3,4)
print(g, g.shape, g.ndim)

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]

 [[25. 26. 27. 28.]
  [29. 30. 31. 32.]
  [33. 34. 35. 36.]]] (3, 3, 4) 3


In [18]:
g1 = g.transpose()
print(g1)

[[[ 1. 13. 25.]
  [ 5. 17. 29.]
  [ 9. 21. 33.]]

 [[ 2. 14. 26.]
  [ 6. 18. 30.]
  [10. 22. 34.]]

 [[ 3. 15. 27.]
  [ 7. 19. 31.]
  [11. 23. 35.]]

 [[ 4. 16. 28.]
  [ 8. 20. 32.]
  [12. 24. 36.]]]


In [19]:
g1 = g.transpose()
g[0,0,0] = 100
print(g1, g1.shape)

[[[100.  13.  25.]
  [  5.  17.  29.]
  [  9.  21.  33.]]

 [[  2.  14.  26.]
  [  6.  18.  30.]
  [ 10.  22.  34.]]

 [[  3.  15.  27.]
  [  7.  19.  31.]
  [ 11.  23.  35.]]

 [[  4.  16.  28.]
  [  8.  20.  32.]
  [ 12.  24.  36.]]] (4, 3, 3)


In [20]:
a1 = np.random.random((2,3))
print(a1, a1.shape)
print(a1.transpose().shape, a1.T.shape)

[[0.2055632  0.23025471 0.19000696]
 [0.30653772 0.98831196 0.70420292]] (2, 3)
(3, 2) (3, 2)


#### 배열의 병합
- 세로 병합 A : (3,5), B: (2, 5) ==> (5,5)
- 가로 병합 A : (5,3), B: (5, 2) ==> (5,5)

In [21]:
a = np.ones((3,5), dtype=np.float32)
b = np.zeros((2,5), dtype=np.float32)
print(a, b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [22]:
c = np.concatenate([a, b])
print(c, c.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] (5, 5)


In [23]:
d = np.concatenate([a.T,b.T], axis=1)
print(d.shape, d)

(5, 5) [[1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 0. 0.]]


### view vs copy

In [24]:
l = [1,2,3,4]
l1 = l
l1[0]=10
print(l)

[10, 2, 3, 4]


In [25]:
l = [1,2,3,4]
l1 = l.copy()
l1[0]=10
print(l)

[1, 2, 3, 4]


### 행렬 연산

In [29]:
a = np.array([[2,3,4],
              [5,6,7]], dtype=np.float32)

b = np.array([[20,21,22],
              [23,24,25]], dtype=np.float32)

In [30]:
print(a+b, a*b)

[[22. 24. 26.]
 [28. 30. 32.]] [[ 40.  63.  88.]
 [115. 144. 175.]]


In [31]:
c = np.dot(a, b.T)
print(c, c.shape)

d = np.matmul(a, b.T)
print(d, d.shape)

[[191. 218.]
 [380. 434.]] (2, 2)
[[191. 218.]
 [380. 434.]] (2, 2)


In [32]:
e = d>300
print(e)
d*e

[[False False]
 [ True  True]]


array([[  0.,   0.],
       [380., 434.]], dtype=float32)

In [33]:
c = np.dot(a, b.T)
print(c, c.shape)

d = np.matmul(a, b.T)
print(d, d.shape)

[[191. 218.]
 [380. 434.]] (2, 2)
[[191. 218.]
 [380. 434.]] (2, 2)


In [34]:
e = d>300 # 조건 검사
print(e) # boolean 행렬 출력
print(d*e) # index가 True인 원소 값만 보존, 나머지는 0으로 치환
print(d[e]) # index가 True인 원소만 출력
print(d[e].astype(np.int32)) # data type을 변환

[[False False]
 [ True  True]]
[[  0.   0.]
 [380. 434.]]
[380. 434.]
[380 434]


In [35]:
a = np.arange(1, 11).reshape(2, -1)
print(a.shape, a[0])

(2, 5) [1 2 3 4 5]


In [41]:
l = [[1,2,3,4], [5,6,7,8]]

print(a[0,:])
print(a[0][:])
# print(l[0,:]) # error
print(l[0][:])

[1 2 3 4 5]
[1 2 3 4 5]
[1, 2, 3, 4]
