## numpy 모듈의 학습

In [2]:
import numpy as np

In [3]:
list1 = [1,2,3]
list2 = [4.0, 5.0, 6.0]
print(list1, list2)

[1, 2, 3] [4.0, 5.0, 6.0]


In [5]:
a, b = np.array(list1, dtype=int), np.array(list2, dtype=np.int32)
print(a, b, type(a), type(b))
print('a 원소 데이터 타입:', type(a[0]))
print('b 원소 데이터 타입:', type(b[0]))

[1 2 3] [4 5 6] <class 'numpy.ndarray'> <class 'numpy.ndarray'>
a 원소 데이터 타입: <class 'numpy.int64'>
b 원소 데이터 타입: <class 'numpy.int32'>


In [6]:
a-b

array([-3, -3, -3])

In [7]:
a*b  # element-wise 연산

array([ 4, 10, 18])

In [9]:
a/b  # element-wise 나눗셈

array([0.25, 0.4 , 0.5 ])

In [10]:
b//a # 정수 나눗셈

array([4, 2, 2])

In [11]:
print(f"a shape: {np.shape(a)}, b shape: {np.shape(b)}")

a shape: (3,), b shape: (3,)


In [12]:
print(a*3, b*4) #bloadcasting

[3 6 9] [16 20 24]


## 무작위 수 (random num) 생성 및 변형

In [13]:
a = np.random.rand(2,3)
print(a, np.shape(a), a.shape)

[[0.3311843  0.73511643 0.30515723]
 [0.90009734 0.19213033 0.18083614]] (2, 3) (2, 3)


In [14]:
b = np.random.randn(2,3)
print(b)

[[ 1.45818419 -0.05611733 -1.09897736]
 [-0.9037183   0.09202723  0.73546954]]


In [15]:
c = np.random.rand(6)
print(c, c.shape)

d = np.random.rand(1,6)
print(d, d.shape)

[0.38190773 0.46484736 0.99341682 0.50861148 0.14308543 0.95917019] (6,)
[[0.57287132 0.39929625 0.69282964 0.74180117 0.03456432 0.2770492 ]] (1, 6)


In [16]:
e = np.random.randint(0, 101, 10)
print(e, e.shape)

[ 2 72 79 96 77 68  8 87 28 47] (10,)


## 형태(모양) 변환

In [17]:
print(a, a.shape)
c3 = a.reshape(-1)  # view 형식만 변경
print(c3, c3.shape)
c3[0] = 1
print(a)

[[0.3311843  0.73511643 0.30515723]
 [0.90009734 0.19213033 0.18083614]] (2, 3)
[0.3311843  0.73511643 0.30515723 0.90009734 0.19213033 0.18083614] (6,)
[[1.         0.73511643 0.30515723]
 [0.90009734 0.19213033 0.18083614]]


In [18]:
print(a, a.shape)
c4 = a.reshape((3,2))  # 원래 a값을 보존하고, a의 형태 (view 형식)만 c2가 가져감
print(c4, c4.shape)
c4[0][0] = 0.5
print(a)

[[1.         0.73511643 0.30515723]
 [0.90009734 0.19213033 0.18083614]] (2, 3)
[[1.         0.73511643]
 [0.30515723 0.90009734]
 [0.19213033 0.18083614]] (3, 2)
[[0.5        0.73511643 0.30515723]
 [0.90009734 0.19213033 0.18083614]]
